dist: precise
language: node_js
sudo: required
branches:
  except:
  - /^v?\d+\.\d+\.\d+$/
before_install:
- if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
script:
- if [ "$TRAVIS_BRANCH" != "master" ]; then npm run test; fi
after_success:
- if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then exit 0; elif [ "$TRAVIS_BRANCH" != "master" ]; then exit 0; fi
- git config --global user.email "xcxncu@gmail.com"
- git config --global user.name "Cheng"
- git config --global push.default simple
- git remote rm origin
- git remote add origin $GH_URL
- git checkout master
- git pull origin master
- "{ sed -nE 's/^[ \\t]*\"version\": \"([0-9]{1,}\\.[0-9]{1,}\\.)[0-9x]{1,}\",$/\\1/p' package.json; git describe --abbrev=0 | sed -E 's/^v([0-9]{1,}\\.[0-9]{1,}\\.)([0-9]{1,})$/\\1 \\2/g'; } | tr \"\\n\" \" \" | awk '{printf($1==$2?\"v\"$2$3+1:\"v\"$1\"0\")}' | xargs -I {} git tag -a {} -m \"{}\"\n"
- npm --no-git-tag-version version from-git
- git push origin master
- git push --tags